/* Generated by Phoenix Tuner X */
package frc.robot.subsystems;

import static edu.wpi.first.units.Units.*;

import java.util.function.Supplier;

import com.ctre.phoenix6.BaseStatusSignal;
import com.ctre.phoenix6.CANBus;
import com.ctre.phoenix6.StatusSignal;
import com.ctre.phoenix6.Utils;
import com.ctre.phoenix6.configs.CurrentLimitsConfigs;
import com.ctre.phoenix6.configs.MotorOutputConfigs;
import com.ctre.phoenix6.configs.TalonFXConfiguration;
import com.ctre.phoenix6.controls.CoastOut;
import com.ctre.phoenix6.controls.VelocityVoltage;
import com.ctre.phoenix6.hardware.TalonFX;
import com.ctre.phoenix6.signals.InvertedValue;
import com.ctre.phoenix6.signals.NeutralModeValue;
import com.ctre.phoenix6.sim.ChassisReference;
import com.ctre.phoenix6.sim.TalonFXSimState;

import edu.wpi.first.math.numbers.N1;
import edu.wpi.first.math.numbers.N2;
import edu.wpi.first.math.system.LinearSystem;
import edu.wpi.first.math.system.plant.DCMotor;
import edu.wpi.first.math.system.plant.LinearSystemId;
import edu.wpi.first.units.measure.*;
import edu.wpi.first.wpilibj.Notifier;
import edu.wpi.first.wpilibj.RobotController;
import edu.wpi.first.wpilibj.simulation.DCMotorSim;
import edu.wpi.first.wpilibj.smartdashboard.Mechanism2d;
import edu.wpi.first.wpilibj.smartdashboard.MechanismLigament2d;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;
import edu.wpi.first.wpilibj2.command.Command;
import edu.wpi.first.wpilibj2.command.SubsystemBase;

public class Intake extends SubsystemBase {
    /** Velocity setpoints for the flywheel. */
    public enum IntakeSetpoint {
        Intake(RotationsPerSecond.of(80), RotationsPerSecond.of(80)),
        Outtake(RotationsPerSecond.of(-70), RotationsPerSecond.of(-70)),
        FeedToShoot(RotationsPerSecond.of(80), RotationsPerSecond.of(-90));

        /** The velocity target of the setpoint. */
        public final AngularVelocity TopIndexTarget;
        public final AngularVelocity GroundIndexTarget;

        private IntakeSetpoint(AngularVelocity TopIndexTarget, AngularVelocity GroundIndexTarget) {
            this.TopIndexTarget = TopIndexTarget;
            this.GroundIndexTarget = GroundIndexTarget;
        }
    }

    private static final int kNumConfigAttempts = 2;

    private static final double kGearRatio = 1;

    /* leader and follower motors */
    private final CANBus kCANBus = new CANBus("*");
    private final TalonFX TopIndex = new TalonFX(21, kCANBus);
    private final TalonFX GroundIndex = new TalonFX(20, kCANBus);

    /* device status signals */
    private final StatusSignal<AngularVelocity> TopIndexVelocity = TopIndex.getVelocity(false);
    private final StatusSignal<Current> TopIndexTorqueCurrent = TopIndex.getTorqueCurrent(false);
    private final StatusSignal<AngularVelocity> GroundIndexVelocity = GroundIndex.getVelocity(false);
    private final StatusSignal<Current> GroundIndexTorqueCurrent = GroundIndex.getTorqueCurrent(false);

    /* controls used by the leader motors */
    private final VelocityVoltage setpointRequest = new VelocityVoltage(0);
    private final CoastOut coastRequest = new CoastOut();

    /* simulation */
    private final DCMotor TopIndexDCMotors = DCMotor.getKrakenX60Foc(2);
    private final LinearSystem<N2, N1, N2> TopIndexFlywheelSystem = LinearSystemId.createDCMotorSystem(TopIndexDCMotors, 0.07, kGearRatio);
    private final DCMotorSim TopIndexFlywheelSim = new DCMotorSim(TopIndexFlywheelSystem, TopIndexDCMotors);
    private final DCMotor GroundIndexDCMotors = DCMotor.getKrakenX60Foc(2);
    private final LinearSystem<N2, N1, N2> GroundIndexFlywheelSystem = LinearSystemId.createDCMotorSystem(GroundIndexDCMotors, 0.07, kGearRatio);
    private final DCMotorSim GroundIndexFlywheelSim = new DCMotorSim(GroundIndexFlywheelSystem, GroundIndexDCMotors);

    private static final double kSimLoopPeriod = 0.002; // 2 ms
    private Notifier simNotifier = null;
    private double lastSimTime = 0.0;

    /* Mechanism2d visualization for flywheel TopIndex */
    private final Mechanism2d TopIndexMech2d = new Mechanism2d(2, 2);
    private final MechanismLigament2d TopIndexFlywheelMech2d = TopIndexMech2d.getRoot("Intake Root TopIndex", 1, 1)
        .append(new MechanismLigament2d("Intake TopIndex", 1, 0));/* Mechanism2d visualization for flywheel GroundIndex */
    private final Mechanism2d GroundIndexMech2d = new Mechanism2d(2, 2);
    private final MechanismLigament2d GroundIndexFlywheelMech2d = GroundIndexMech2d.getRoot("Intake Root GroundIndex", 1, 1)
        .append(new MechanismLigament2d("Intake GroundIndex", 1, 0));

    /** Configs common across all motors. */
    private static final TalonFXConfiguration motorTalonFXInitialConfigs = new TalonFXConfiguration()
        .withMotorOutput(
            new MotorOutputConfigs()
                .withNeutralMode(NeutralModeValue.Brake)
        )
        .withCurrentLimits(
            new CurrentLimitsConfigs()
                .withStatorCurrentLimit(Amps.of(120))
                .withStatorCurrentLimitEnable(true)
        );

    /** Configs for {@link #TopIndex}. */
    private final TalonFXConfiguration TopIndexConfigs = motorTalonFXInitialConfigs.clone()
        .withMotorOutput(
            motorTalonFXInitialConfigs.MotorOutput.clone()
                .withInverted(InvertedValue.CounterClockwise_Positive)
        )
        .withFeedback(
            motorTalonFXInitialConfigs.Feedback.clone()
                .withSensorToMechanismRatio(1)
        )
        .withSlot0(
            motorTalonFXInitialConfigs.Slot0.clone()
                .withKP(0)
                .withKI(0)
                .withKD(0)
                .withKS(0)
                .withKV(0.12)
                .withKA(0)
        );

    /** Configs for {@link #GroundIndex}. */
    private final TalonFXConfiguration GroundIndexConfigs = motorTalonFXInitialConfigs.clone()
        .withMotorOutput(
            motorTalonFXInitialConfigs.MotorOutput.clone()
                .withInverted(InvertedValue.CounterClockwise_Positive)
        )
        .withFeedback(
            motorTalonFXInitialConfigs.Feedback.clone()
                .withSensorToMechanismRatio(1)
        )
        .withSlot0(
            motorTalonFXInitialConfigs.Slot0.clone()
                .withKP(0)
                .withKI(0)
                .withKD(0)
                .withKS(0)
                .withKV(0.12)
                .withKA(0)
        );

    public Intake() {
        for (int i = 0; i < kNumConfigAttempts; ++i) {
            var status = TopIndex.getConfigurator().apply(TopIndexConfigs);
            if (status.isOK()) break;
        }
        for (int i = 0; i < kNumConfigAttempts; ++i) {
            var status = GroundIndex.getConfigurator().apply(GroundIndexConfigs);
            if (status.isOK()) break;
        }


        /* set the default command to neutral output */
        setDefaultCommand(coastIntake());

        SmartDashboard.putData("Intake TopIndex", TopIndexMech2d);

        SmartDashboard.putData("Intake GroundIndex", GroundIndexMech2d);

        if (Utils.isSimulation()) {
            startSimThread();
        }
    }

    /**
     * @return The TopIndexVelocity of the flywheel
     */
    public AngularVelocity getTopIndexVelocity() {
        return TopIndexVelocity.getValue();
    }

    /**
     * @return The TopIndexTorqueCurrent of the flywheel
     */
    public Current getTopIndexTorqueCurrent() {
        return TopIndexTorqueCurrent.getValue();
    }

    /**
     * @return The GroundIndexVelocity of the flywheel
     */
    public AngularVelocity getGroundIndexVelocity() {
        return GroundIndexVelocity.getValue();
    }

    /**
     * @return The GroundIndexTorqueCurrent of the flywheel
     */
    public Current getGroundIndexTorqueCurrent() {
        return GroundIndexTorqueCurrent.getValue();
    }

    /**
     * Drives the flywheel to the provided velocity setpoint.
     *
     * @param setpoint Function returning the setpoint to apply
     * @return Command to run
     */
    public Command setTarget(Supplier<IntakeSetpoint> target) {
        return run(() -> {
            IntakeSetpoint t = target.get();
            setpointRequest.withVelocity(t.TopIndexTarget);
            TopIndex.setControl(setpointRequest);
            setpointRequest.withVelocity(t.GroundIndexTarget);
            GroundIndex.setControl(setpointRequest);
        });
    }

    /**
     * Stops driving the Intake. We use coast so not energy is used during the braking event.
     *
     * @return Command to run
     */
    public Command coastIntake() {
        return run(() -> {
            TopIndex.setControl(coastRequest);
            GroundIndex.setControl(coastRequest);
        });
    }

    @Override
    public void periodic() {
        /* refresh all status signals */
        BaseStatusSignal.refreshAll(
            TopIndexVelocity,
            TopIndexTorqueCurrent,
            GroundIndexVelocity,
            GroundIndexTorqueCurrent
        );

        TopIndexFlywheelMech2d.setLength(
            TopIndexVelocity.getValueAsDouble() / 100.0
        );

        GroundIndexFlywheelMech2d.setLength(
            GroundIndexVelocity.getValueAsDouble() / 100.0
        );
    }

    private void startSimThread() {
        TopIndex.getSimState().Orientation = ChassisReference.CounterClockwise_Positive;
        TopIndex.getSimState().setMotorType(TalonFXSimState.MotorType.KrakenX60);
        GroundIndex.getSimState().Orientation = ChassisReference.CounterClockwise_Positive;
        GroundIndex.getSimState().setMotorType(TalonFXSimState.MotorType.KrakenX60);

        lastSimTime = Utils.getCurrentTimeSeconds();

        /* Run simulation at a faster rate so PID gains behave more reasonably */
        simNotifier = new Notifier(() -> {
            /* Calculate the time delta */
            final double currentTime = Utils.getCurrentTimeSeconds();
            final double deltaTime = currentTime - lastSimTime;
            lastSimTime = currentTime;

            final var TopIndexSim = TopIndex.getSimState();
            final var GroundIndexSim = GroundIndex.getSimState();

            /* First set the supply voltage of all the devices */
            TopIndexSim.setSupplyVoltage(RobotController.getBatteryVoltage());
            GroundIndexSim.setSupplyVoltage(RobotController.getBatteryVoltage());

            /* Then calculate the new velocity of the simulated flywheel */
            TopIndexFlywheelSim.setInputVoltage(TopIndexSim.getMotorVoltage());
            TopIndexFlywheelSim.update(deltaTime);
            GroundIndexFlywheelSim.setInputVoltage(GroundIndexSim.getMotorVoltage());
            GroundIndexFlywheelSim.update(deltaTime);

            /* Apply the new rotor velocity to the motors (before gear ratio) */
            TopIndexSim.setRawRotorPosition(
                Radians.of(TopIndexFlywheelSim.getAngularPositionRad() * kGearRatio)
            );
            TopIndexSim.setRotorVelocity(
                RadiansPerSecond.of(TopIndexFlywheelSim.getAngularVelocityRadPerSec() * kGearRatio)
            );
            GroundIndexSim.setRawRotorPosition(
                Radians.of(GroundIndexFlywheelSim.getAngularPositionRad() * kGearRatio)
            );
            GroundIndexSim.setRotorVelocity(
                RadiansPerSecond.of(GroundIndexFlywheelSim.getAngularVelocityRadPerSec() * kGearRatio)
            );
        });
        simNotifier.startPeriodic(kSimLoopPeriod);
    }
}